vim.g.mapleader = " "
vim.keymap.set('n', 'k', 'gk')
vim.keymap.set('n', 'j', 'gj')
vim.keymap.set('n', '<Up>', '<Nop>')
vim.keymap.set('n', '<Down>', '<Nop>')
vim.keymap.set('n', '<Left>', '<Nop>')
vim.keymap.set('n', '<Right>', '<Nop>')
------ Window Splitting --
vim.keymap.set('n', 'ss', ':<C-u>sp<CR>')
vim.keymap.set('n', 'sv', ':<C-u>vs<CR>')
vim.keymap.set('n', 'sq', ':<C-u>q<CR>')
vim.keymap.set('n', 'sQ', ':<C-u>bd<CR>')
vim.keymap.set('n', 'sj', '<C-w>j')
vim.keymap.set('n', 'sk', '<C-w>k')
vim.keymap.set('n', 'sl', '<C-w>l')
vim.keymap.set('n', 'sh', '<C-w>h')
vim.keymap.set('n', 'sJ', '<C-w>J')
vim.keymap.set('n', 'sK', '<C-w>K')
vim.keymap.set('n', 'sL', '<C-w>L')
vim.keymap.set('n', 'sH', '<C-w>H')
vim.keymap.set('n', 's>', '<C-w>>')
vim.keymap.set('n', 's<', '<C-w><')
vim.keymap.set('n', 's+', '<C-w>+')
vim.keymap.set('n', 's-', '<C-w>-')
---- Tab manipulation --
vim.keymap.set('n', 'st', ':<C-u>tabnew<CR>')
vim.keymap.set('n', 'sl', 'gt')
vim.keymap.set('n', 'sh', 'gT')
-- vim.keymap.set()
-- vim.keymap.set()
-- vim.keymap.set()
-- vim.keymap.set()
-- vim.keymap.set()
-- vim.keymap.set()
-- vim.keymap.set()
-- vim.keymap.set()
-- vim.keymap.set()
-- vim.keymap.set()
-- vim.keymap.set()
-- vim.keymap.set()
-- vim.keymap.set()
-- vim.keymap.set()
-- vim.keymap.set()
-- vim.keymap.set()
-- vim.keymap.set()
-- vim.keymap.set()
-- vim.keymap.set()
-- vim.keymap.set()
-- vim.keymap.set()
-- vim.keymap.set()
-- vim.keymap.set()
-- vim.keymap.set()
-- vim.keymap.set()
-- vim.keymap.set()
-- vim.keymap.set()
-- vim.keymap.set()
-- vim.keymap.set()
