-- set Keymap not related Plugin
vim.keymap.set('n', '<Left>'  , '<Nop>'             , { silent = true, remap = true })
vim.keymap.set('v', '<Left>'  , '<Nop>'             , { silent = true, remap = true })
vim.keymap.set('i', '<Left>'  , '<Nop>'             , { silent = true, remap = true })
vim.keymap.set('n',  '<Up>'   , '<Nop>'             , { silent = true, remap = true })
vim.keymap.set('v',  '<Up>'   , '<Nop>'             , { silent = true, remap = true })
vim.keymap.set('i',  '<Up>'   , '<Nop>'             , { silent = true, remap = true })
vim.keymap.set('n',  '<Down>' , '<Nop>'             , { silent = true, remap = true })
vim.keymap.set('v',  '<Down>' , '<Nop>'             , { silent = true, remap = true })
vim.keymap.set('i',  '<Down>' , '<Nop>'             , { silent = true, remap = true })
vim.keymap.set('n', '<Right>' , '<Nop>'             , { silent = true, remap = true })
vim.keymap.set('v', '<Right>' , '<Nop>'             , { silent = true, remap = true })
vim.keymap.set('i', '<Right>' , '<Nop>'             , { silent = true, remap = true })
vim.keymap.set('n', 'j'       , 'gj'                , { silent = true, remap = true })
-- vim.keymap.set('v', 'j'       , 'gj'                , { silent = true, remap = true })
-- vim.keymap.set('i', 'j'       , 'gj'                , { silent = true, remap = true })
vim.keymap.set('n', 'k'       , 'gk'                , { silent = true, remap = true })
-- vim.keymap.set('i', 'k'       , 'gk'                , { silent = true, remap = true })
-- vim.keymap.set('i', 'k'       , 'gk'                , { silent = true, remap = true })
vim.keymap.set('n', 's'       , '<Nop>'             , { silent = true, remap = true })
vim.keymap.set('n', 'ss'      , '<C-u>:split<CR>'   , { silent = true, remap = true })
vim.keymap.set('n', 'sv'      , '<C-u>:vsplit<CR>'           , { silent = true, remap = true })
vim.keymap.set('n', 'sq'      , '<C-u>:q<CR>'                , { silent = true, remap = true })
vim.keymap.set('n', 'sQ'      , '<C-u>:bd<CR>'               , { silent = true, remap = true })
vim.keymap.set('n', 'sh'      , '<C-w>h'            , { silent = true, remap = true })
vim.keymap.set('n', 'sj'      , '<C-w>j'            , { silent = true, remap = true })
vim.keymap.set('n', 'sk'      , '<C-w>k'            , { silent = true, remap = true })
vim.keymap.set('n', 'sl'      , '<C-w>l'            , { silent = true, remap = true })
vim.keymap.set('n', 'sH'      , '<C-w>H'            , { silent = true, remap = true })
vim.keymap.set('n', 'sJ'      , '<C-w>J'            , { silent = true, remap = true })
vim.keymap.set('n', 'sK'      , '<C-w>K'            , { silent = true, remap = true })
vim.keymap.set('n', 'sL'      , '<C-w>L'            , { silent = true, remap = true })
vim.keymap.set('n', 's>'      , '<C-w>>'            , { silent = true, remap = true })
vim.keymap.set('n', 's<'      , '<C-w><'            , { silent = true, remap = true })
vim.keymap.set('n', 's+'      , '<C-w>+'            , { silent = true, remap = true })
vim.keymap.set('n', 's-'      , '<C-w>-'            , { silent = true, remap = true })
vim.keymap.set('n', 'st'      , '<C-u>:tabnew<CR>'  , { silent = true, remap = true })
vim.keymap.set('n', 'sn'      , 'gt'                , { silent = true, remap = true })
vim.keymap.set('n', 'sp'      , 'gT'                , { silent = true, remap = true })
vim.keymap.set('i', 'jj'      , '<Esc>'             , { silent = true,              })
