# =========================
# ===  General settings  ===
# ==========================

# === move the status bar to top ===
set-option -g status-position top

# === Fix MessedUp Window Numbering ===
set-option -g renumber-windows on
set -g base-index 1
setw -g pane-base-index 1

# ===       vi mode         ===
set-window-option -g mode-keys vi
set -g default-terminal "screen-256color"
set -g default-shell "$SHELL"

# ===        force os52     ===
set -as terminal-overrides ',rxvt-*:Ms=\E]52;%p1%s;%p2%s\007'

# ==============================
# ===       keymap          ===
# ==============================

# ===       prefixkey       ===
unbind C-b
set -g prefix C-q
bind C-q send-prefix

# === Resize Shortcuts       ===
bind-key -r < resize-pane -L 3
bind-key -r > resize-pane -R 3
bind-key -r + resize-pane -U 1
bind-key -r - resize-pane -D 1

# === Split Window          ===
bind-key % split-window -h -c "#{pane_current_path}"
bind-key '"' split-window -v -c "#{pane_current_path}"

# === Reload config Shortcuts ===
bind-key r source-file ~/.tmux.conf \; display "Config reloaded"

# === Themes   ===
# set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavour 'mocha'
## catppuccin config
set -g @catppuccin_window_left_separator "█"
set -g @catppuccin_window_middle_separator " "
set -g @catppuccin_window_right_separator_inverse "yes"
set -g @catppuccin_window_right_separator "█"
set -g @catppuccin_window_number_position "left"
set -g @catppuccin_window_default_fill "none"
set -g @catppuccin_window_current_fill "all"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_text "#W"

set -g @catppuccin_directory_color "yellow"
set -g @catppuccin_status_modules_right "directory application"
set -g @catppuccin_status_modules_left "session"
set -g @catppuccin_status_left_separator  "█"
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_right_separator_inverse "yes"
set -g @catppuccin_status_fill "all"
set -g @catppuccin_status_connect_separator "no"
# === enable activity alerts ===
setw -g monitor-activity on

# === generouus history limit
set-option -g history-limit 50000
# === show messages for 4 seconds instead
set -g display-time 4000

# ============================
# ===       Plugins        ===
# ============================

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugis/tmux-pain-control'
set -g @plugin 'sainnhe/tmux-fzf'
TMUX_FZF_LAUNCH_KEY="C-f"
TMUX_FZF_OPTIONS='--height 40% -w 60% --border --inline-info --color=border:#94e2d5 --preview "bat --style=numbers --color=always --line-range :200 {}" --preview-window=+{2}+3/2 --color=fg:#a9b1d6,hl:#f5c2e7,fg+:#a6e3a1,bg+:#1a1b26,hl+:#fab387'
# プラグインマネージャの初期化
run '~/.tmux/plugins/tpm/tpm'

