#!/bin/sh

set -e

echo "Setting up dotfiles..."

echo "Installing Homebrew..."
if [ ! -f /opt/homebrew/bin/brew ]; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

echo "Cloning dotfiles repository..."
if [ ! -d ~/dotfiles ]; then
  cd ~
  git clone https://github.com/TKG2800/dotfiles.git
fi

if [ ! -d ~/.tmux/plugins/tpm ]; then
   git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
else
   echo "TPM is already installed."
fi

echo "Installing packages from Brewfile..."
brew bundle -v --file=~/dotfiles/Brewfile

echo "Stowing dotfiles..."
stow -v -d ~/dotfiles/packages -t ~ alacritty git zsh tmux starship vim nvim

echo "Dotfiles setup complete!"
