#!/bin/sh
set -e

if [ ! -f /opt/homebrew/bin/brew ]; then
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

brew bundle -v --file=~/dotfiles/Brewfile

if [ ! -d ~/dotfiles ]; then
    cd ~
    git clone git@github.com:TKG2800/dotfiles.git
fi

if [ ! -f ~/.tmux/plugins/tpm/tpm ]; then
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

if [ ! -d ~/.config ]; then
   cd ~
   mkdir .config
fi
stow -v -d ~/dotfiles/packages -t ~ ghostty zsh tmux git vim nvim lazygit starship
if [ ! -d ~/.local/share/zinit ]; then
  bash -c "$(curl --fail --show-error --silent --location https://raw.githubusercontent.com/zdharma-continuum/zinit/HEAD/scripts/install.sh)"
fi
